### ISSUE TITLE
Can't squash commits

### ISSUE THREAD

**Issue by IhanaMies** [KeenSoftwareHouse/SpaceEngineers#245]
I get a lot of conflicts. Why can't github rename all the commits into one clean commit?

**Comment by zrisher** [comment]
Because commits represent functionally separate changes to the code base. If you're maintaining a development branch and having issues rebasing onto master, the best advice I can give is to squash your own changes into a few commits as possible that deal with separate logic as well. 

The number of commits Keen pushes to master doesn't matter - if even one of them touches a file you've changed, you're likely to have a conflict. However, the number of times you have to deal with that conflict while rebasing depends entirely on your code.

if you have 10 commits that change the same file you will have to deal with the conflict 10 times when rebasing. If you instead had just a few of your own commits, and only one of them touched that file, then you would only have to deal with the conflict once.

**Comment by IhanaMies** [comment]
Good to hear. So in case of #244 it shouldn't be a problem even with that amount of commits, since overall in changes only 18 files.

**Comment by zrisher** [comment]
No, that is way too many commits - you have 10 or so commits marked "Add Inventory Mass", those should all be rolled into one commit. You also have a bunch of "Revert" commits, those should never make it into master unless they're reverting things that were already in master. Combine them with the commits you were reverting instead and you'll have a zero delta.

**Comment by IhanaMies** [comment]
Got it done. Fixing the conflicts was the way.
