### ISSUE TITLE
Autopilot Enhancments

### ISSUE THREAD

**Issue by yannick9906** [KeenSoftwareHouse/SpaceEngineers#405]
Making the Autopilot able to use the jump drive and fly around asteroids instead of crashing with them.

**Comment by Jimmacle** [comment]
Personally, I feel like this is not necessary because the current system provides valid engineering challenges to Space Engineers. Your proposed features would remove all drawbacks to using autopilot, which IMO is poorly balanced.

**Comment by jpcsupplies** [comment]
On the topic -
Autopilot does have some odd quirks..   I notice if i autopilot a small ship near an asteroid it flies around it, and usually avoids things... but does tend to fly sideways or angularly instead of the defined forward "direction"  other people have speculated it somehow gets its "front" from the map grid not the ship grid from observed behaviour.

Also -
If I autopilot two or more large ships at once along a set of common way points, they seem to lose the ability to behave consistent with the rules of physics, or avoid things.. particularly each other.  Which is odd as two ships that accellerate at different speeds, from different starting points due to different mass/power/engines should travel at different speeds, yet they somehow managed to syncronise, and arrive at the same waypoints at once and crash.   This says to me there is some shared element in the code between autopiloted ships, which probably shouldn't be, resulting in the odd effect of syncronising arrival times even in significantly different ships.

As for improved avoidance and jump drives, there was an auto pilot mod developed prior to vanilla autopilot that allowed players to link in sensor blocks to avoid things..   so short of factoring in sensor data in remote blocks running auto pilot, i would suggest mods already allow avoidance so the main game doesn't need it urgently.    Likewise mods can jump ships too; so that removes the need for that too. 

In either case carefully placed waypoints has the same effect anyway.   Fly around objects, or make the ship pass through a "portal" type  mods for the desired effect.    

Basic physics and "forward" direction may need looking at tho.

**Comment by anilhaksever** [comment]
Being not able to use forward direction actions is also something I found challenging when I try to write ingame scripts. Right now I can send any ship to anywhere but for docking I still need old fashion azimuth calculation and thruster override.
