### ISSUE TITLE
Proposal: Trading connector block

### ISSUE THREAD

**Issue by Metal10k** [KeenSoftwareHouse/SpaceEngineers#443]
So I am sure I am not the only one who has looked at Exploration Enhancement Mod and been inspired greatly, but also frustrated by the clunkiness, and thus the fact there is currently no mechanism for two grids of different ownership/faction to ‘communicate’ with one another. What the modders have done is extremely brilliant considering the constraints, but I think there may be a better way to bring this functionality to the core game.

If you have not checked it out, i recommend you do so at:
http://steamcommunity.com/sharedfiles/filedetails/?id=531659576

What I am proposing is a connector block that works very much like how the current connector block does today, the big difference being that one side (let's call this the ‘client’) drives the transfer of resources in both directions interactively based on some form of trading GUI. 

The other side of the connection (lets call this the ‘server’ for now) might consist of either a separate block, or simply a separate configuration on the same block type, thus allowing it to ‘serve’ resources/components from a connected grid at a configured price. Prices and items available to trade would be configured inside the serving block. 

A ‘client’ trading block and a ‘server’ trading block would be able to connect to one another just how connectors do today, even though the player will only have ownership of one of these. The link between the two would ensure secure and performant transactions between the two grid systems, thus allowing modders to build trading outposts, etc.

Unfortunately it doesn't appear like this can be created in a mod as of today as new UI would be required to drive this system, hence why I am posting here. Having had a bit of a look through the source code, it appears that a good and obvious starting point would be the MyShipConnector class as a lot of the connection/grid scanning logic is already in place.Quite a lot of new code would have to be written for the handshake and exchange mechanisms, but there definitely appears to be a lot of shared functionality, so perhaps this could/should be refactored out?

If there is interest, I would be happy to take a deeper dive myself, although I may need a little guidance here. I wanted to get the idea out there anyway since lots of people are interested in trading, but nobody is talking about building it yet.

**Comment by acbabis** [comment]
You could give the Trade block a GUI similar to the Sorter block. Instead of white-listing items that can pass through, you would add entries of the form "X Item A -> Y Item B." Rather than make offers after connecting, you make persistent offers beforehand like a store would. This way, the trading process itself is stateless.

Someone connected through their Trade block would be able to see a list of available trades in their own Trade block's terminal entry, and click an "accept" button next to an entry to make the exchange.

The Trade block has two inventories. One is for storing items for sale and automatically pulls listed items so that each listed entry is viable. The other inventory is for receiving only, can't have items placed in it by the player, and is automatically emptied into available containers. If someone's Trade block is too full to complete a trade, the corresponding entry is disabled until the receiving inventory is empty enough. Similarly, an entry is disabled if either trader's Trade block doesn't actually contain the items for sale. Under a minimal implementation, a buyer has to manually drag their items into the Trade block, unless they happen to have their own entry offering the same item they're paying with, in which case the items are already there.

When someone clicks the "accept" button, the items are immediately swapped between the inventories, circumventing grid permissions and preventing potential scamming issues that could arise from disconnecting after accepting a trade.

Advantages:
- Relies mostly on existing concepts
- Probably requires less refactoring than other approaches
- Since trade is immediate, player's can't pull away from a trade without paying

Drawbacks:
- Circumventing grid permissions is probably bad
- A buyer would have to manually drag items into the "For Sale" inventory before making a purchase, unless the Trade block is smart enough to stage items from other people's offers.

**Comment by mexmer** [comment]
this is not suggestion forum.

**Comment by JamesK89** [comment]
Before doing something like this I would wait until we have server authoritative networking code merged and working. In my opinion the current peer-to-peer model is ripe for abuse and synchronization issues with something like this.

**Comment by Spartan322** [comment]
Please put suggestions on the forums, github's issue tracker is not made for suggestions like this

**Comment by acbabis** [comment]
@Spartan322 @mexmer It sounds like the OP is interested in making a branch with this feature. Wouldn't this be the place to discuss this?

**Comment by mexmer** [comment]
nope, unless it's part of his code, or he is working on code for that, it should go to forum.
forum has higher population to discuss suggestions, not mentioning forum is one and only official channel for game suggestions and game bug reports.

**Comment by Metal10k** [comment]
My intention was to have an architectural viability/implementation discussion, and github is the place for talk about code. As you are probably aware most open source projects are very precious about their architecture, and writing code without discussing it first (unless its trivial) is a recipe for disaster. I don't really feel like wasting 3 days creating a pull request that will simply be rejected because it doesn't fit in with the overall vision. 

Are you suggesting that the team is not open to contributions of this manner?

**Comment by mexmer** [comment]
if by team you mean KSW the no, they don't take any suggestion from here.

they check PRs, and if there is issue related to them, they check it, but for suggestions and other stuff forum is official way.

as you might have noticed even RCS modification is discussed more on forum, than here. multithreding improvement is also more discussed on forums, although some relevant posts and replies are also here, but multithreading also had PR for it.

you can put your suggestion under sourcecode section on forums, if you want to discuss relevant and needed source changes.

**Comment by Metal10k** [comment]
Ok no worries, I will close this.
