### ISSUE TITLE
Current source isn't buildable as is.

### ISSUE THREAD

**Issue by Doriphor** [KeenSoftwareHouse/SpaceEngineers#530]
The currently included version of

`\3rd\HavokWrapper_SE\release\x86\HavokWrapper.dll`

has an issue with its HkWorld class: its Gravity property lacks a setter, which prevents building because

`\sources\sandbox.game\engine\physics\myphysics.cs`

is attempting a write (line 1516).

**Comment by LeonidasCZ** [comment]
Hello since the end of 32bit support we are not able to update this library and Havok's licence prevents us from uploading 64bit library with the source. We are looking into possibilities. Feel free to come to our Discord server where is a dedicated channel for GitHub https://discord.gg/0hIE7GirODUqhfIg

**Comment by mexmer** [comment]
you can find on forums, how to make 64bit build

**Comment by Doriphor** [comment]
@LeonidasCZ Ah so that's why. So I guess the readme is outdated?

@mexmer Thanks! I'll check it out!
