### ISSUE TITLE
Repository is no longer updated

### ISSUE THREAD

**Issue by ShooShoSha** [KeenSoftwareHouse/SpaceEngineers#584]
The last commit (a109106fc0ded66bdd5da70e099646203c56550f) was Jan 6 and the published version is updated consistently.

It seems Keen Software House has stopped publishing to the public repo based on the [commit](https://github.com/KeenSoftwareHouse/SpaceEngineers/graphs/commit-activity), [code frequency](https://github.com/KeenSoftwareHouse/SpaceEngineers/graphs/code-frequency), [issues](https://github.com/KeenSoftwareHouse/SpaceEngineers/issues), and [unresolved pull requests](https://github.com/KeenSoftwareHouse/SpaceEngineers/pulls).

Please update the repository.

**Comment by DanAtkinson** [comment]
More concerning is that their commit history has been dumped on [pastebin](https://pastebin.com/FdMqrnLy) for whatever reason.

**Comment by mexmer** [comment]
@DanAtkinson there is nothing concernig about that. anyone can do that, since it's on github. probly someone wanted to share repo history with someone.

anyways you might want to check forums or discord

it's my impression that github will no longer be updated, mind they work at least on 3 branches at same time - stable one, experimental one (builds from stable and experimental are available on steam), and like every dev team out there , they will probly have one or more internal branches for new stuff.

while it would be nice, if they do update github at least with source of stable version, my understanding is, that there currently no person dedicated for that, and since it's time consuming task to sync repos ... you know your answer.

btw. don't expect any official answer here, if you need something "official" go to forums.

**Comment by nfowler-1** [comment]
@mexmer That's a shame since I am completely willing to volunteer my time to fix small issues.  Working with mods and the engine gives me experience in an area different from my normal automation and app dev area.

**Comment by JJRcop** [comment]
Earlier this month, Marek Rosa posted on [his blog](http://blog.marekrosa.org/2017/08/statement-on-space-engineers-github.html) that the GitHub will not be updated anymore and that they will give internal SVN access to accomplished modders.

**Comment by JamesK89** [comment]
Keen won't say why this change is happening and an employee on Reddit said that it wasn't really Marek's call so I'm guessing an investor complained or they did it so they could integrate SteamWorks into the gameplay for the TF2-esque hat-ititus drops into the game they added in a recent update.


This might be a crazy idea but maybe it is possible the community could fork the existing code here on GitHub and develop independently of Keen's version. We'll probably end up stuck on the same version of the engine as the last official GitHub release though.

**Comment by mccorkle** [comment]
Though this code is on github, I don't think the intent was ever to make
the engine open source (and allow forking or independent development).

If you have the itch to work on the game, don't let that stop you though.
Fork it -- add something cool -- and tell the Keen team about it on Discord
or Reddit where they hang out.

**Comment by Krienas** [comment]
That may be coincidence, but updates had stopped when LeonidasCZ had left Keen. Explanation can be very simple (like almost always is) - simply nobody had stepped in to take care of this task.

**Comment by JJRcop** [comment]
@JamesK89 the source code was never open source, it was made available to the public under a proprietary license. If someone forked this they would not be able to distribute it for free and it would be required to be a mod of Space Engineers, which means all interested users would need to buy Space Engineers on Steam in order to run the forked version.

It could still be done, but there is no point, as modders can just make mods for the maintained, updated game on the Steam Workshop.

**Comment by JamesK89** [comment]
@JJRcop I never made the claim the code base was FLOSS.
@mccorkle The engine code is obviously not part of the code base Keen shared so obviously we're talking about the game logic here which is in its own assembly loaded by the engine.

@Krienas If I recall correctly an employee on Reddit said that the entire process was automated so this decision had nothing to do with convenience.


I'm kind of thinking maybe that Keen just simply regrets their decision and is back pedaling but created the cool kids club as damage control. Granted there is a ModAPI but what you can do with it is extremely limited compared to when you have source code access to the game itself. I had some ideas I wanted to try out but obviously I waited too long unless I can fork and use the existing available code base to get into the cool kids club.

**Comment by ShooShoSha** [comment]
@JJRcop thanks for that link. I'm closing this issue as that post clearifies what this repo is used for from now on:

> we have decided to change the way we distribute our source code. The source on GitHub will receive no more updates, though it will remain online as a reference.
