### ISSUE TITLE
Idea about upgrading LCDs

### ISSUE THREAD

**Issue by stafyniaksacha** [KeenSoftwareHouse/SpaceEngineers#74]
There is some idea for improving LCD screens : 
- Able to choose a monospacing font
- Able to set colors (background/foreground) of each characters (and not only screen)
- Access to the display matrix of the screen

**Comment by kapitanov** [comment]
> Able to choose a monospacing font

+1, monospace font is a must have feature

**Comment by MMaster** [comment]
I would prefer moddable font. I was already looking into the code, but unfortunately LCD does not have font property at all. Render function does not take font as argument, but I did not look into it any deeper. If we would be able to specify font per LCD definition we would be able to do much more than just monospace font.

**Comment by kapitanov** [comment]
Looks like the actual text rendering takes place [here](https://github.com/KeenSoftwareHouse/SpaceEngineers/blob/07519235308594be64a1a96254897942206899bf/Sources/VRage.Render/MyDebugDraw.cs#L809), but unfortunately the font is hardcoded right there to `MyRender.GetDebugFont()` value.

The rendering parameters go all the way down:
* `MyTextPanel`,
* `MyRenderComponentTextPanel`,
* `MyRenderProxy`
* `MyRenderMessageDrawTextToMaterial`
* `MyRender`
* `MyDebugDraw`

And the font pops up only on the very last stage of pipeline. However it looks like an easy job to pass an optional `MyFont` object though the call chain.

Access to the display matrix should be easy too since the text buffer is stored right in `MyTextPanel`. A few lines of code should be enough to help represent the text buffer as a matrix. However display matrix access doesn't make much sense to me until we have a monospace font.

Per-character color attributes will definitely take a lot of work and might kill the performance. It would be an awesome feature anyway - imagine Norton Commander-style interfaces made inside SE game :)

**Comment by cwc** [comment]
For reference, game fonts are currently hardcoded in [MySandboxGame](https://github.com/KeenSoftwareHouse/SpaceEngineers/blob/a41226a238e66b66cc2ef4461982d769be126ba1/Sources/Sandbox.Game/MySandboxGame.cs#L1039-L1059). Perhaps the font descriptions could be loaded from a file?

**Comment by kapitanov** [comment]
OK, I've got a working prototype that allows you to select normal or monospace font. But things are not as nice as they might be:

* Game has a hardcoded list of available fonts and they are loaded on game startup, not on game session startup. Fonts are also identified by a hardcoded enumeration MyFontEnum. That makes it impossible to allow loading custom fonts from mods, or at least this would require a significant code changes. 
* Game has very few built-in fonts and all of them are basically the same font rendered with different color and scale. So it wouldn't be not enough just to change game code - game content should be updated as well. Not sure if KSH will do that for us - they got plenty of work to do already.
* I haven't figured out how to generate 100% correct font bitmaps - I was able to build one but looks like some characters are missing. I've got some workarounds that help game not to crash but it's not a good way to go. I have a couple of ideas how to fix font generation, will try them later.

In case someone want the code - let me know and I'll push it to my repo.

**Comment by stafyniaksacha** [comment]
Hi @kapitanov, I'm interested, I will see if I can do something 
but did we can do a PR for game resources such as fonts ? I have found them in the content game directory which is not versioned :(

**Comment by kapitanov** [comment]
@stafyniaksacha, the only _normal_ way to deal with custom fonts as I see it is to enable font loading from workshop mods. But for now we can just push the modded fonts into separate repository. Of course you'll have to copy them into game directory manually. I'll do that for my test monospace font it a few days.

The roadmap for font modding support (as I see it) looks like that:
1. Change `MyFontEnum` from hardcoded enumeration into something more dynamic (that's a hard one)
2. Enable game to load extra fonts from mods when loading the game session (we can take a look at code that loads modded textures and do something similar for modded fonts)
3. Add some infrastructure to apply custom fonts to LCD panel (that task should be an easy one once tasks 1 and 2 are done)

When it's all done we should be able to create mods for LCD panel fonts.

**Comment by kapitanov** [comment]
Got a first implementation of monospace fonts [here](https://github.com/kapitanov/SpaceEngineers/commit/84411b). 
This implementation requires a font named `monospace` to be present in game content folder.
I've got scripts that generate and install fonts [here](https://github.com/kapitanov/SE_CustomFonts)

However this implementation is not moddable so it will require support from KSH to include a monospace font into game resources.

**Comment by THDigi** [comment]
It would be nice if they supported transparent backgrounds and even semi-transparent text, if the material is marked as a 'GLASS'.

**Comment by croxis** [comment]
It could also work as a functional hologram block with some fancy texture/shader effects.

**Comment by stafyniaksacha** [comment]
Look to be done, closing issue
